baseURL = "https://protcenkoroman.github.io/draughts/"
languageCode = "ru"
title = "Draughts"
theme = "beautifulhugo"
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -110
